# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"rangeof": "00_core.ipynb",
         "make_grid": "00_core.ipynb",
         "convert_poly_coords": "00_core.ipynb",
         "affine_transform_gdf": "00_core.ipynb",
         "gdf_to_px": "00_core.ipynb",
         "georegister_px_df": "00_core.ipynb",
         "non_max_suppression_fast": "00_core.ipynb",
         "cone_v": "00_core.ipynb",
         "cut_cone_v": "00_core.ipynb",
         "Tiler": "01_preprocessing.ipynb",
         "untile_vector": "01_preprocessing.ipynb",
         "COCOProcessor": "01_preprocessing.ipynb"}

modules = ["core.py",
           "preprocessing.py"]

doc_url = "https://jaeeolma.github.io/drone_detector/"

git_url = "https://github.com/jaeeolma/drone_detector/tree/{branch}/"

def custom_doc_links(name): return None
