# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"rangeof": "00_utils.ipynb",
         "non_max_suppression_fast": "00_utils.ipynb",
         "cone_v": "00_utils.ipynb",
         "cut_cone_v": "00_utils.ipynb",
         "make_grid": "01_tiling.ipynb",
         "Tiler": "01_tiling.ipynb",
         "untile_vector": "01_tiling.ipynb",
         "untile_raster": "01_tiling.ipynb",
         "convert_poly_coords": "02_coordinates.ipynb",
         "affine_transform_gdf": "02_coordinates.ipynb",
         "gdf_to_px": "02_coordinates.ipynb",
         "georegister_px_df": "02_coordinates.ipynb",
         "resize_binary_mask": "03_coco.ipynb",
         "close_contour": "03_coco.ipynb",
         "binary_mask_to_polygon": "03_coco.ipynb",
         "COCOProcessor": "03_coco.ipynb",
         "poly_IoU": "04_postprocessing.ipynb",
         "poly_intersection_over_area": "04_postprocessing.ipynb",
         "show_im_mask_pred": "05_visualizations.ipynb",
         "plot_grid_preds_actuals_raws": "05_visualizations.ipynb",
         "show_raw_mask_pred": "05_visualizations.ipynb"}

modules = ["utils.py",
           "tiling.py",
           "coordinates.py",
           "coco.py",
           "postproc.py",
           "visualizations.py"]

doc_url = "https://jaeeolma.github.io/drone_detector/"

git_url = "https://github.com/jaeeolma/drone_detector/tree/master/"

def custom_doc_links(name): return None
