# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/06_detection.ipynb (unless otherwise specified).

__all__ = ['DetectionModel']

# Cell

class DetectionModel():


    def __init__():
        pass

    def fit_one_cycle():
        pass

