# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/07_segmentation.ipynb (unless otherwise specified).

__all__ = ['label_with_matching_fname', 'SegmentationModel']

# Cell

def label_with_matching_fname(fn, path): return f'{path}/{fn.stem}{fn.suffix}'

# Cell

class SegmentationModel():

    def __init__():
        pass


    def fit():
        pass

    def predict():
        pass