# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/07_segmentation.ipynb (unless otherwise specified).

__all__ = ['SegmentationModel']

# Cell

class SegmentationModel():

    def __init__():
        pass


    def fit():
        pass

    def predict():
        pass