# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_utils.ipynb.

# %% auto 0
__all__ = ['rangeof', 'fix_multipolys', 'cone_v', 'cut_cone_v']

# %% ../nbs/00_utils.ipynb 3
from .imports import *

# %% ../nbs/00_utils.ipynb 5
def rangeof(iterable):
    "Equivalent for range(len(iterable))"
    return range(len(iterable))

# %% ../nbs/00_utils.ipynb 6
def fix_multipolys(multipoly:shapely.geometry.MultiPolygon):
    """Convert MultiPolygon to a single Polygon. 
    The resulting Polygon has the exterior boundaries of the largest geometry of the MultiPolygon"""
    temp_poly = None
    max_area = 0
    for geom in multipoly.geoms:
        area = geom.area
        if area > max_area:
            max_area = area
            temp_poly = geom
    return shapely.geometry.Polygon(temp_poly.exterior)

# %% ../nbs/00_utils.ipynb 8
def cone_v(r:float, h:float) -> float:
    "V = (Ah)/3"
    A = np.pi * r**2
    V = (A * h) / 3
    return V

def cut_cone_v(r_1:float, r_2:float, h:float):
    "V = (h(A + sqrt(A*A') + A))/3"
    A_1 = np.pi * r_1**2
    A_2 = np.pi * r_2**2
    V = (h*(A_1 + np.sqrt(A_1 * A_2) + A_2))/3
    return V

