source "https://rubygems.org"

gem 'github-pages', group: :jekyll_plugins

# Added at 2019-11-25 10:11:40 -0800 by jhoward:

gem "jekyll", ">= 3.9", '<4'
gem "kramdown", ">= 2.3.1"
gem "jekyll-remote-theme"
gem "webrick", "~> 1.7"
